analyzer_volume_grouping.o: $(NODE_CLUSTERING_TEST_DIR)/analyzer_volume_grouping.f90 m_precision.o m_constants.o m_machine_parameter.o calypso_mpi.o t_mesh_data.o t_comm_table.o t_geometry_data.o t_group_data.o t_surface_data.o t_edge_data.o m_work_time.o m_array_for_send_recv.o m_default_file_prefix.o t_ctl_data_volume_grouping.o t_control_param_vol_grping.o t_1d_repartitioning_work.o t_repartition_by_volume.o set_istack_4_domain_block.o repart_in_xyz_by_volume.o set_repartition_group_name.o t_file_IO_parameter.o t_read_mesh_data.o t_shape_functions.o t_jacobians.o t_fem_gauss_int_coefs.o t_next_node_ele_4_node.o mpi_load_mesh_data.o mesh_file_IO.o copy_mesh_structures.o append_group_data.o calypso_mpi_int.o calypso_mpi_real.o const_jacobians_3d.o parallel_FEM_mesh_init.o output_test_mesh.o set_table_4_RHS_assemble.o nod_phys_send_recv.o solver_SR_type.o transfer_to_long_integers.o set_parallel_file_name.o int_volume_of_single_domain.o
	$(F90) -c $(F90OPTFLAGS) $<
main_volume_grouping.o: $(NODE_CLUSTERING_TEST_DIR)/main_volume_grouping.f90 m_precision.o calypso_mpi.o analyzer_volume_grouping.o
	$(F90) -c $(F90OPTFLAGS) $<
repart_in_xyz_by_volume.o: $(NODE_CLUSTERING_TEST_DIR)/repart_in_xyz_by_volume.f90 m_precision.o m_constants.o t_geometry_data.o quicksort.o
	$(F90) -c $(F90OPTFLAGS) $<
set_istack_4_domain_block.o: $(NODE_CLUSTERING_TEST_DIR)/set_istack_4_domain_block.f90 m_precision.o t_control_param_vol_grping.o t_geometry_data.o calypso_mpi.o calypso_mpi_int.o calypso_mpi_real.o transfer_to_long_integers.o
	$(F90) -c $(F90OPTFLAGS) $<
set_repartition_group_name.o: $(NODE_CLUSTERING_TEST_DIR)/set_repartition_group_name.f90 m_precision.o m_constants.o t_geometry_data.o t_control_param_vol_grping.o set_parallel_file_name.o
	$(F90) -c $(F90OPTFLAGS) $<
t_1d_repartitioning_work.o: $(NODE_CLUSTERING_TEST_DIR)/t_1d_repartitioning_work.f90 m_precision.o t_control_param_vol_grping.o t_geometry_data.o
	$(F90) -c $(F90OPTFLAGS) $<
t_control_param_vol_grping.o: $(NODE_CLUSTERING_TEST_DIR)/t_control_param_vol_grping.f90 m_precision.o t_file_IO_parameter.o calypso_mpi.o m_error_IDs.o m_machine_parameter.o t_ctl_data_volume_grouping.o m_file_format_switch.o set_control_platform_data.o set_ctl_parallel_platform.o set_num_domain_each_dir.o
	$(F90) -c $(F90OPTFLAGS) $<
t_ctl_data_volume_grouping.o: $(NODE_CLUSTERING_TEST_DIR)/t_ctl_data_volume_grouping.f90 m_precision.o m_machine_parameter.o t_ctl_data_4_platforms.o t_ctl_data_4_FEM_mesh.o t_read_control_elements.o t_control_array_integer.o t_control_array_character.o t_control_array_charaint.o skip_comment_f.o calypso_mpi.o bcast_4_platform_ctl.o calypso_mpi_int.o bcast_control_arrays.o
	$(F90) -c $(F90OPTFLAGS) $<
t_repartition_by_volume.o: $(NODE_CLUSTERING_TEST_DIR)/t_repartition_by_volume.f90 m_precision.o t_geometry_data.o calypso_mpi.o t_mesh_data.o t_control_param_vol_grping.o calypso_mpi_real.o int_volume_of_single_domain.o solver_SR_type.o t_1d_repartitioning_work.o t_group_data.o set_istack_4_domain_block.o repart_in_xyz_by_volume.o set_repartition_group_name.o
	$(F90) -c $(F90OPTFLAGS) $<

