analyzer_node_cluster_test.o: $(NODE_CLUSTERING_TEST_DIR)/analyzer_node_cluster_test.f90 m_precision.o m_machine_parameter.o calypso_mpi.o t_mesh_data.o t_comm_table.o t_geometry_data.o t_group_data.o t_surface_data.o t_edge_data.o m_work_time.o m_array_for_send_recv.o m_default_file_prefix.o t_ctl_data_mesh_test.o t_control_param_mesh_test.o copy_mesh_structures.o mesh_file_IO.o nod_phys_send_recv.o set_parallel_file_name.o mpi_load_mesh_data.o const_jacobians_3d.o parallel_FEM_mesh_init.o output_test_mesh.o set_table_4_RHS_assemble.o t_file_IO_parameter.o t_read_mesh_data.o t_shape_functions.o t_jacobians.o t_fem_gauss_int_coefs.o t_multi_node_clustering.o const_element_comm_table.o int_volume_of_single_domain.o
	$(F90) -c $(F90OPTFLAGS) $<
analyzer_repartition_test.o: $(NODE_CLUSTERING_TEST_DIR)/analyzer_repartition_test.f90 m_precision.o m_machine_parameter.o calypso_mpi.o t_mesh_data.o t_comm_table.o t_geometry_data.o t_group_data.o t_surface_data.o t_edge_data.o m_work_time.o m_array_for_send_recv.o m_default_file_prefix.o t_ctl_data_mesh_test.o t_control_param_mesh_test.o copy_mesh_structures.o mesh_file_IO.o nod_phys_send_recv.o set_parallel_file_name.o mpi_load_mesh_data.o const_jacobians_3d.o parallel_FEM_mesh_init.o output_test_mesh.o set_table_4_RHS_assemble.o t_file_IO_parameter.o t_read_mesh_data.o t_shape_functions.o t_jacobians.o t_fem_gauss_int_coefs.o t_repartition_test.o const_element_comm_table.o int_volume_of_single_domain.o
	$(F90) -c $(F90OPTFLAGS) $<
main_node_clustering_test.o: $(NODE_CLUSTERING_TEST_DIR)/main_node_clustering_test.f90 m_precision.o calypso_mpi.o analyzer_node_cluster_test.o
	$(F90) -c $(F90OPTFLAGS) $<
main_repartition_test.o: $(NODE_CLUSTERING_TEST_DIR)/main_repartition_test.f90 m_precision.o calypso_mpi.o analyzer_repartition_test.o
	$(F90) -c $(F90OPTFLAGS) $<
matmul_tests_4_smp.o: $(NODE_CLUSTERING_TEST_DIR)/matmul_tests_4_smp.f90 m_precision.o m_constants.o cal_minmax_and_stacks.o matmul_for_legendre_trans.o
	$(F90) -c $(F90OPTFLAGS) $<
t_multi_node_clustering.o: $(NODE_CLUSTERING_TEST_DIR)/t_multi_node_clustering.f90 m_precision.o m_constants.o t_mesh_data.o t_next_node_ele_4_node.o t_node_clustering_list.o int_volume_of_single_domain.o copy_mesh_structures.o
	$(F90) -c $(F90OPTFLAGS) $<
t_node_clustering_list.o: $(NODE_CLUSTERING_TEST_DIR)/t_node_clustering_list.f90 m_precision.o m_constants.o t_geometry_data.o t_next_node_ele_4_node.o cal_mesh_position.o quicksort.o
	$(F90) -c $(F90OPTFLAGS) $<
t_repartition_test.o: $(NODE_CLUSTERING_TEST_DIR)/t_repartition_test.f90 calypso_mpi.o calypso_mpi_real.o calypso_mpi_int.o m_precision.o m_constants.o t_mesh_data.o t_next_node_ele_4_node.o t_node_clustering_list.o int_volume_of_single_domain.o copy_mesh_structures.o
	$(F90) -c $(F90OPTFLAGS) $<

