# /bin/sh

GTK3_CFLAGS=  -I/opt/homebrew/Cellar/gtk+3/3.24.37/include/gtk-3.0 -I/opt/homebrew/Cellar/glib/2.76.2/include/gio-unix-2.0 -I/opt/homebrew/Cellar/cairo/1.16.0_5/include/cairo -I/opt/homebrew/Cellar/libepoxy/1.5.10/include -I/opt/homebrew/Cellar/pango/1.50.14/include/pango-1.0 -I/opt/homebrew/Cellar/harfbuzz/7.1.0/include/harfbuzz -I/opt/homebrew/Cellar/pango/1.50.14/include/pango-1.0 -I/opt/homebrew/Cellar/fribidi/1.0.12/include/fribidi -I/opt/homebrew/Cellar/harfbuzz/7.1.0/include/harfbuzz -I/opt/homebrew/Cellar/graphite2/1.3.14/include -I/opt/homebrew/Cellar/atk/2.38.0/include/atk-1.0 -I/opt/homebrew/Cellar/cairo/1.16.0_5/include/cairo -I/opt/homebrew/Cellar/pixman/0.42.2/include/pixman-1 -I/opt/homebrew/Cellar/fontconfig/2.14.2/include -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/libxcb/1.15_1/include -I/opt/homebrew/Cellar/libxrender/0.9.11/include -I/opt/homebrew/Cellar/libxext/1.3.5/include -I/opt/homebrew/Cellar/libx11/1.8.4/include -I/opt/homebrew/Cellar/libxcb/1.15_1/include -I/opt/homebrew/Cellar/libxau/1.0.11/include -I/opt/homebrew/Cellar/libxdmcp/1.1.4/include -I/opt/homebrew/Cellar/gdk-pixbuf/2.42.10_1/include/gdk-pixbuf-2.0 -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/Cellar/libtiff/4.5.0/include -I/opt/homebrew/Cellar/zstd/1.5.5/include -I/opt/homebrew/Cellar/jpeg-turbo/2.1.5.1/include -I/opt/homebrew/Cellar/glib/2.76.2/include -I/opt/homebrew/Cellar/glib/2.76.2/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.76.2/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.42/include -I/opt/homebrew/Cellar/xorgproto/2022.2/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/ffi -I/usr/X11/include

GTK3_LIBS=    -L/opt/homebrew/Cellar/gtk+3/3.24.37/lib -L/opt/homebrew/Cellar/pango/1.50.14/lib -L/opt/homebrew/Cellar/harfbuzz/7.1.0/lib -L/opt/homebrew/Cellar/atk/2.38.0/lib -L/opt/homebrew/Cellar/cairo/1.16.0_5/lib -L/opt/homebrew/Cellar/gdk-pixbuf/2.42.10_1/lib -L/opt/homebrew/Cellar/glib/2.76.2/lib -L/opt/homebrew/opt/gettext/lib -lgtk-3 -lgdk-3 -Wl,-framework,Cocoa -Wl,-framework,Carbon -Wl,-framework,CoreGraphics -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk

mpicc -O3 -Wall -g -fopenmp  -D_REENTRANT -c -I. $(GTK3_CFLAGS) \
/Users/matsui/git/Kemorin_MHD/MHD/programs/TESTS/GTK3_test/file_dialog.c

mpif90 -O3 -Wall -g -fopenmp  -D_REENTRANT -I. $(GTK3_CFLAGS) \
-o control_GTK file_dialog.o \
 $(GTK3_LIBS)
