analyzer_test_crs.o: $(SOLVERTEST_DIR)/analyzer_test_crs.f90 m_precision.o t_geometry_data.o t_comm_table.o t_crs_matrix.o t_iccg_parameter.o t_ctl_data_solver_test.o t_solver_SR.o m_work_time.o calypso_mpi.o input_control_solver_test.o crs_matrix_io.o solve_by_crs_solver.o
	$(F90) -c $(F90OPTFLAGS) $<
analyzer_test_djds.o: $(SOLVERTEST_DIR)/analyzer_test_djds.f90 m_precision.o t_geometry_data.o t_comm_table.o t_crs_matrix.o t_iccg_parameter.o t_ctl_data_solver_test.o t_solver_SR.o calypso_mpi.o input_control_solver_test.o crs_matrix_io.o solve_precond_DJDS.o copy_matrix_2_djds_array.o t_solver_djds.o
	$(F90) -c $(F90OPTFLAGS) $<
crs_matrix_io.o: $(SOLVERTEST_DIR)/crs_matrix_io.f90 m_precision.o calypso_mpi.o t_geometry_data.o t_comm_table.o t_crs_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
input_control_solver_test.o: $(SOLVERTEST_DIR)/input_control_solver_test.f90 m_precision.o m_machine_parameter.o t_ctl_data_solver_test.o t_crs_matrix.o t_iccg_parameter.o calypso_mpi.o t_read_control_elements.o skip_comment_f.o calypso_mpi_int.o bcast_4_solver_ctl.o bcast_control_arrays.o crs_matrix_io.o set_parallel_file_name.o
	$(F90) -c $(F90OPTFLAGS) $<
m_sample_matrices.o: $(SOLVERTEST_DIR)/m_sample_matrices.f90 m_precision.o
	$(F90) -c $(F90OPTFLAGS) $<
main_test_crs.o: $(SOLVERTEST_DIR)/main_test_crs.f90 m_precision.o calypso_mpi.o analyzer_test_crs.o
	$(F90) -c $(F90OPTFLAGS) $<
main_test_djds.o: $(SOLVERTEST_DIR)/main_test_djds.f90 m_precision.o calypso_mpi.o analyzer_test_djds.o
	$(F90) -c $(F90OPTFLAGS) $<
solve_by_crs_solver.o: $(SOLVERTEST_DIR)/solve_by_crs_solver.f90 m_precision.o calypso_mpi.o t_solver_SR.o t_comm_table.o t_geometry_data.o t_crs_matrix.o solver.o solver33.o solverNN.o
	$(F90) -c $(F90OPTFLAGS) $<
t_ctl_data_solver_test.o: $(SOLVERTEST_DIR)/t_ctl_data_solver_test.f90 m_precision.o calypso_mpi.o m_machine_parameter.o t_read_control_elements.o t_ctl_data_4_solvers.o t_control_array_integer.o t_control_array_character.o skip_comment_f.o
	$(F90) -c $(F90OPTFLAGS) $<
test_lubands.o: $(SOLVERTEST_DIR)/test_lubands.f90 m_precision.o m_ludcmp.o m_ludcmp_band.o m_ludcmp_3band.o lubksb_357band.o
	$(F90) -c $(F90OPTFLAGS) $<
testlu_5band.o: $(SOLVERTEST_DIR)/testlu_5band.f90 m_precision.o m_sample_matrices.o m_ludcmp.o m_ludcmp_5mat.o m_ludcmp_bmat.o m_ludcmp_band.o lubksb_357band.o
	$(F90) -c $(F90OPTFLAGS) $<
testmt_multi.o: $(SOLVERTEST_DIR)/testmt_multi.f90 m_precision.o m_ludcmp_3band.o lubksb_357band.o lubksb_357band_mul.o
	$(F90) -c $(F90OPTFLAGS) $<
testmt_single.o: $(SOLVERTEST_DIR)/testmt_single.f90 m_precision.o m_ludcmp.o m_ludcmp_3band.o lubksb_357band.o
	$(F90) -c $(F90OPTFLAGS) $<

