fortran_png_test.o: $(GRAPHIC_TEST_DIR)/fortran_png_test.f90 m_precision.o t_png_file_access.o convert_real_rgb_2_bite.o png_test_from_f.o
	$(F90) -c $(F90OPTFLAGS) $<
parallel_png_to_quilt.o: $(GRAPHIC_TEST_DIR)/parallel_png_to_quilt.F90 m_precision.o calypso_mpi.o calypso_mpi_char.o calypso_mpi_int.o MPI_ascii_data_IO.o m_calypso_mpi_IO.o t_calypso_mpi_IO_param.o t_png_file_access.o t_MPI_quilt_bitmap_IO.o write_bmp_image.o output_image_sel_4_png.o transfer_to_long_integers.o set_parallel_file_name.o mpi_write_quilt_BMP_file.o
	$(F90) -c $(F90OPTFLAGS) $(F90CPPFLAGS) $<
png_to_bmp_f.o: $(GRAPHIC_TEST_DIR)/png_to_bmp_f.F90 t_png_file_access.o write_bmp_image.o
	$(F90) -c $(F90OPTFLAGS) $(F90CPPFLAGS) $<
test_bmp_images.o: $(GRAPHIC_TEST_DIR)/test_bmp_images.f90 m_precision.o write_bmp_image.o
	$(F90) -c $(F90OPTFLAGS) $<

#
check_fontshape.o: \
  $(MHDDIR)/programs/TESTS/graphic_test/check_fontshape.c \
  $(MHDDIR)/C_src/CORE_C/numbers_to_bin_c.h \
  $(MHDDIR)/C_src/CORE_C/ysglfontdata.h
	$(CC) -c $(OPTFLAGS) $(C_INCLUDE) $<
test_read_bmp_c.o: \
  $(MHDDIR)/programs/TESTS/graphic_test/test_read_bmp_c.c \
  $(MHDDIR)/C_src/CORE_C/read_image_2_bmp.h \
  $(MHDDIR)/C_src/CORE_C/calypso_param_c.h \
  $(MHDDIR)/C_src/CORE_C/write_image_2_png.h \
  $(MHDDIR)/C_src/CORE_C/write_image_2_bmp.h
	$(CC) -c $(OPTFLAGS) $(C_INCLUDE) $<
test_read_png_c.o: \
  $(MHDDIR)/programs/TESTS/graphic_test/test_read_png_c.c \
  $(MHDDIR)/C_src/CORE_C/read_image_2_png.h \
  $(MHDDIR)/C_src/CORE_C/write_image_2_png.h \
  $(MHDDIR)/C_src/CORE_C/calypso_param_c.h \
  $(MHDDIR)/C_src/CORE_C/write_image_2_bmp.h
	$(CC) -c $(OPTFLAGS) $(C_INCLUDE) $<
test_read_psf_data.o: \
  $(MHDDIR)/programs/TESTS/graphic_test/test_read_psf_data.c \
  $(MHDDIR)/C_src/CORE_C/m_psf_data_4_viewer_c.h \
  $(MHDDIR)/C_src/CORE_C/calypso_param_c.h \
  $(MHDDIR)/C_src/CORE_C/skip_comment_c.h \
  $(MHDDIR)/C_src/CORE_C/t_psf_edge_connect_c.h \
  $(MHDDIR)/C_src/CORE_C/t_surf_edge_hash_c.h \
  $(MHDDIR)/C_src/CORE_C/read_psf_data_viewer_c.h \
  $(MHDDIR)/C_src/CORE_C/take_normal_psf_c.h \
  $(MHDDIR)/C_src/CORE_C/cal_surface_center_normal_c.h \
  $(MHDDIR)/C_src/CORE_C/coordinate_converter_c.h
	$(CC) -c $(OPTFLAGS) $(C_INCLUDE) $<
test_wt_png_c.o: \
  $(MHDDIR)/programs/TESTS/graphic_test/test_wt_png_c.c \
  $(MHDDIR)/C_src/CORE_C/write_image_2_png.h \
  $(MHDDIR)/C_src/CORE_C/calypso_param_c.h
	$(CC) -c $(OPTFLAGS) $(C_INCLUDE) $<
