analyzer_refine.o: $(REFINE_MAINDIR)/analyzer_refine.f90 m_precision.o m_constants.o t_mesh_data.o t_geometry_data.o t_group_data.o t_surface_data.o t_edge_data.o t_comm_table.o t_control_data_4_refine.o t_refined_element_data.o t_control_param_4_refiner.o load_mesh_data.o set_nnod_for_ele_by_type.o set_control_id_4_refiner.o refinment_info_IO.o m_geometry_constants.o t_refined_node_id.o set_nnod_4_ele_by_type.o set_element_refine_flag.o set_all_refine_flags.o count_nnod_for_refine.o set_refined_node_id.o set_local_position_4_refine.o set_refined_position.o refined_nod_2_mesh_data.o const_refined_connectivity.o const_refined_group.o set_refine_flags_4_tri.o const_refine_interpolate.o find_hanging_surface.o copy_mesh_structures.o const_mesh_information.o
	$(F90) -c $(F90OPTFLAGS) $<
analyzer_refine_itp_para.o: $(REFINE_MAINDIR)/analyzer_refine_itp_para.f90 m_precision.o m_constants.o m_machine_parameter.o t_control_param_refine_para.o t_mesh_data_4_merge.o t_control_data_refine_para.o t_para_refine_itp_tables.o t_work_const_itp_table.o set_parallel_mesh_in_1pe.o m_interpolate_table_IO.o itp_table_IO_select_4_zlib.o num_nod_ele_merge_by_type.o merge_domain_local_by_type.o t_interpolate_table.o t_mesh_data.o t_mesh_data_with_pointer.o t_merged_geometry_data.o const_parallel_itp_table.o
	$(F90) -c $(F90OPTFLAGS) $<
refine_interpolate_para_tbl.o: $(REFINE_MAINDIR)/refine_interpolate_para_tbl.f90 m_precision.o analyzer_refine_itp_para.o
	$(F90) -c $(F90OPTFLAGS) $<
refiner.o: $(REFINE_MAINDIR)/refiner.f90 m_precision.o analyzer_refine.o
	$(F90) -c $(F90OPTFLAGS) $<

