add_magne_ini_4_plane.o: $(PLANE_MODEL_DIR)/add_magne_ini_4_plane.f90 m_precision.o m_constants.o m_base_field_labels.o t_size_of_cube.o t_field_data_IO.o t_mesh_data.o t_geometry_data.o t_time_data.o t_file_IO_parameter.o t_mesh_data_4_merge.o t_ctl_data_4_cub_kemo.o t_ctl_data_plane_fft.o t_control_param_plane_mesh.o t_setting_4_ini.o set_parallel_file_name.o mesh_IO_select.o set_field_file_names.o field_file_IO.o set_field_to_restart.o copy_mesh_structures.o
	$(F90) -c $(F90OPTFLAGS) $<
cub_kemo.o: $(PLANE_MODEL_DIR)/cub_kemo.f90 m_precision.o t_ctl_data_4_cub_kemo.o t_control_param_plane_mesh.o t_size_of_cube.o cubmesh_311.o
	$(F90) -c $(F90OPTFLAGS) $<
cub_kemo_quad.o: $(PLANE_MODEL_DIR)/cub_kemo_quad.f90 m_precision.o cube_mesh_fiile_IO.o t_mesh_data.o t_size_of_cube.o t_neib_range_cube.o t_cube_position.o t_local_node_id_cube.o t_ctl_data_4_cub_kemo.o t_control_param_plane_mesh.o t_filter_work_cubmesh.o t_filter_data_4_plane.o t_filter_elength.o t_ctl_data_plane_fft.o set_cube_node_quad.o set_cube_ele_connect.o set_import_cube.o write_nod_grp_cube.o write_ele_grp_cube.o write_surf_grp_cube.o neib_nod_cube.o neib_edge_cube.o merge_periodic_comm_table.o mesh_data_IO.o m_fem_mesh_labels.o
	$(F90) -c $(F90OPTFLAGS) $<
generate_initial_4_plane.o: $(PLANE_MODEL_DIR)/generate_initial_4_plane.f90 m_precision.o m_constants.o m_base_field_labels.o t_mesh_data.o t_geometry_data.o t_time_data.o t_field_data_IO.o t_file_IO_parameter.o t_mesh_data_4_merge.o t_ctl_data_4_cub_kemo.o t_ctl_data_plane_fft.o t_control_param_plane_mesh.o t_size_of_cube.o t_setting_4_ini.o set_parallel_file_name.o mesh_IO_select.o set_field_file_names.o field_file_IO.o set_field_to_restart.o copy_mesh_structures.o t_phys_data.o
	$(F90) -c $(F90OPTFLAGS) $<

