PSF_control_label_to_c.o: $(VIZ_F2003_DIR)/PSF_control_label_to_c.f90 m_precision.o t_control_array_character.o m_section_coef_flags.o m_pvr_control_labels.o
	$(F90) -c $(F90OPTFLAGS) $<
PVR_control_label_to_c.o: $(VIZ_F2003_DIR)/PVR_control_label_to_c.f90 m_precision.o t_control_array_character.o m_pvr_control_labels.o m_control_fline_flags.o
	$(F90) -c $(F90OPTFLAGS) $<

