#
	$(CC) -c $(OPTFLAGS_GL) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS_GL) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS_GL) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS_GL) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS_GL) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS_GL) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS_GL) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS_GL) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS_GL) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS_GL) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS_GL) $(C_INCLUDE) $<
