t_fft_test_data.o: $(FFT_TEST_DIR)/t_fft_test_data.f90 m_precision.o m_constants.o m_machine_parameter.o
	$(F90) -c $(F90OPTFLAGS) $<
test_FFT.o: $(FFT_TEST_DIR)/test_FFT.f90 m_precision.o m_constants.o m_machine_parameter.o m_FFT_selector.o t_FFT_selector.o t_fft_test_data.o
	$(F90) -c $(F90OPTFLAGS) $<
test_FFTPACK5.o: $(FFT_TEST_DIR)/test_FFTPACK5.f90 m_precision.o m_constants.o m_machine_parameter.o t_fft_test_data.o t_FFTPACK5_wrapper.o
	$(F90) -c $(F90OPTFLAGS) $<
test_FFTW3.o: $(FFT_TEST_DIR)/test_FFTW3.f90 m_precision.o m_constants.o m_machine_parameter.o t_FFTW_wrapper.o t_multi_FFTW_wrapper.o t_fft_test_data.o
	$(F90) -c $(F90OPTFLAGS) $<
test_ISPACK1_FFT.o: $(FFT_TEST_DIR)/test_ISPACK1_FFT.f90 m_precision.o m_constants.o m_machine_parameter.o t_ispack_FFT_wrapper.o t_fft_test_data.o
	$(F90) -c $(F90OPTFLAGS) $<
test_ISPACK3_FFT.o: $(FFT_TEST_DIR)/test_ISPACK3_FFT.f90 m_precision.o m_constants.o m_machine_parameter.o t_ispack3_FFT_wrapper.o t_fft_test_data.o
	$(F90) -c $(F90OPTFLAGS) $<

