OBJS = spnjcb.o spnini.o spmini.o spclap.o spclam.o spswnl.o spswck.o \
       spswnv.o spswcv.o spswli.o spswlv.o spswnw.o spswnx.o spswbl.o \
       spswhv.o spswhi.o spswhw.o spswhx.o spswcx.o
TMPSRC = spswhw.f spswhx.f spswnw.f spswnx.f
include ../../Mkinclude.sub
