calypso_c_binding.o: $(F2003DIR)/calypso_c_binding.f03 m_precision.o
	$(F90) -c $(F90OPTFLAGS) $<
gzip_defleate.o: $(F2003DIR)/gzip_defleate.f03 m_precision.o
	$(F90) -c $(F90OPTFLAGS) $<
gzip_infleate.o: $(F2003DIR)/gzip_infleate.f03 m_precision.o
	$(F90) -c $(F90OPTFLAGS) $<

