copy_MHD_4_pole_trans.o: $(MHD_SNAPSHOT_DIR)/copy_MHD_4_pole_trans.f90 m_precision.o m_constants.o t_spheric_rtp_data.o t_geometry_data.o t_phys_address.o t_phys_data.o m_machine_parameter.o copy_pole_field_sph_trans.o
	$(F90) -c $(F90OPTFLAGS) $<

