!
!      module write_interpolated_node
!
      module write_interpolated_node
!
!     Written by H. Matsui on Sep., 2006
!
!
      use m_precision
!
      implicit  none
!
!      subroutine s_write_interpolate_node_file(my_rank)
!
!------------------------------------------------------------------
!
      contains
!
!------------------------------------------------------------------
!
      subroutine s_write_interpolate_node_file(my_rank)
!
      use m_ctl_params_4_gen_table
      use m_read_mesh_data
      use domain_data_IO
      use node_geometry_IO
      use set_parallel_file_name
!
      integer (kind = kint), intent(in) :: my_rank
!
!
      call add_int_suffix(my_rank, itp_node_file_head, mesh_file_name)
!
      write(*,*) 'ascii mesh file: ', trim(mesh_file_name)
      open (input_file_code, file = mesh_file_name,                     &
     &      form = 'formatted')
!
      write(input_file_code,*) '!' 
      write(input_file_code,*)                                          &
     &    '!     node position generated by interpolation'
      write(input_file_code,*) '!' 
      write(input_file_code,*) '! '
      write(input_file_code,*) '! 1.parallel information'
      write(input_file_code,*) '! '
!
!
      call write_domain_info(input_file_code)
!
      write(input_file_code,*) '! '
      write(input_file_code,*)                                          &
     &      '! 2.mesh information (nodes and elements in partition)'
      write(input_file_code,*) '! '
      write(input_file_code,*) '! 2.1 node (position) '
      write(input_file_code,*) '! '
!
      call write_geometry_info(input_file_code)
!
      close(input_file_code)
!
      end subroutine s_write_interpolate_node_file
!
!  ---------------------------------------------------------------------
!
      end module write_interpolated_node
