#
array_for_sorting_test.o: \
  $(MHDDIR)/programs/TESTS/Sorting_test/array_for_sorting_test.c \
  $(MHDDIR)/programs/TESTS/Sorting_test/array_for_sorting_test.h \
  $(MHDDIR)/C_src/CORE_C/quicksort_c.h
	$(CC) -c $(OPTFLAGS) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS) $(C_INCLUDE) $<
integer_sorting_tests.o: \
  $(MHDDIR)/programs/TESTS/Sorting_test/integer_sorting_tests.c \
  $(MHDDIR)/programs/TESTS/Sorting_test/integer_sorting_tests.h \
  $(MHDDIR)/programs/TESTS/Sorting_test/array_for_sorting_test.h \
  $(MHDDIR)/C_src/CORE_C/quicksort_c.h \
  $(MHDDIR)/C_src/CORE_C/bitonic_sort_c.h \
  $(MHDDIR)/C_src/CORE_C/bitonic_sort_int_pthread.h
	$(CC) -c $(OPTFLAGS) $(C_INCLUDE) $<
	$(CC) -c $(OPTFLAGS) $(C_INCLUDE) $<
